import com.ftn.sbnz.kjar.model.facts.UserFact;
import com.ftn.sbnz.kjar.model.facts.MovieFact;
import com.ftn.sbnz.kjar.model.KeywordStats;
import com.ftn.sbnz.kjar.model.MovieStats;

rule "Compute MovieStats score"
no-loop true
when
    $user : UserFact($uid : id)
    $movie : MovieFact($mid : movieId, $keywords : keywords)
    $stat  : KeywordStats(userId == $uid, $kw : keyword, $count : count, $avg : averageRating)
    eval($keywords.contains($kw))
then
    double score = $count * $avg;
    System.out.println("MovieStats for user " + $uid + ", movie " + $mid + ", score " + score);
    insert(new MovieStats($uid, $mid, score));
end
