package rules;

import com.ftn.sbnz.kjar.model.facts.UserFact;
import com.ftn.sbnz.kjar.model.facts.MovieFact;
import com.ftn.sbnz.kjar.model.level_3.MovieStats;
import com.ftn.sbnz.kjar.model.level_4.Recommendation;
import java.util.List;


agenda-group "A4"

// A4 - Base recommendation from MovieStats
rule "Create Recommendation"
when
    $stats : MovieStats(
        $userId : userId,
        $movieId : movieId,
        $title : title,
        $score : score
    )

    not Recommendation(
        userId == $userId,
        movieId == $movieId
    )
then
    insert(new Recommendation($userId, $movieId, $title, $score));
end

// A4 - Boost if movie contains a preferred keyword (+5 per match)
rule "Boost Preferred Keyword"
when
    $user  : UserFact($userId : id, $prefKeywords : preferredKeywords)

    $rec   : Recommendation(
        userId == $userId,
        keywordBoosted == false
    )

    $movie : MovieFact(
        id == $rec.movieId,
        $keywords : keywords
    )

    $kw : String() from $keywords

    eval($prefKeywords != null && $prefKeywords.contains($kw))
then
    $rec.setScore($rec.getScore() + 5.0);
    $rec.setKeywordBoosted(true);
    update($rec);
end

// A4 - Boost if movie matches a preferred genre (+5 per match)
rule "Boost Preferred Genre"
when
    $user  : UserFact($userId : id, $prefGenres : preferredGenres)

    $rec   : Recommendation(
        userId == $userId,
        genreBoosted == false
    )

    $movie : MovieFact(
        id == $rec.movieId,
        $genres : genres
    )

    $g : String() from $genres

    eval($prefGenres != null && $prefGenres.contains($g))
then
    $rec.setScore($rec.getScore() + 5.0);
    $rec.setGenreBoosted(true);
    update($rec);
end

// A4 – Boost if movie is on watchlist (+3)
rule "Boost Watchlisted"
when
    $user : UserFact($userId : id, $watchlisted : watchlistedMovieIds)

    $rec : Recommendation(
        userId == $userId,
        movieId memberOf $watchlisted,
        watchlistBoosted == false
    )
then
    $rec.setScore($rec.getScore() + 3.0);
    $rec.setWatchlistBoosted(true);
    update($rec);
end

rule "DEBUG Recommendation"
when
    $r : Recommendation()
then
    System.out.println(
        "REC -> user=" + $r.getUserId() +
        " movie=" + $r.getMovieId() +
        " score=" + $r.getScore()
    );
end
